### ISSUE TITLE
Create a test scenario

### ISSUE THREAD

**Issue by nikitazigman** [nikitazigman/linz_sumo_scenario#1]
We need a small but complex enough scenario to test a future data converter. 

The task:
Crop a suitable part of the map and generate a sumo test scenario using the [netconvert](https://sumo.dlr.de/docs/netconvert.html)

**Comment by amirhesama** [comment]
[St.Magdalena_Linz.zip](https://github.com/user-attachments/files/15952679/St.Magdalena_Linz.zip)
This is one cropped area of Linz, I do not know if it is good or not but how can I upload the real data of Linz traffic into that for real traffic simulation?

**Comment by nikitazigman** [comment]
@amirhesama 
Hello, could you please consider using Git Pull requests instead of zip files for future submissions? I was able to run your work, and I have a few questions:
1. Did you utilize the City of Linz source files? Upon reviewing your net file, I noticed that the routes' IDs have different formats. I do not think we will be able to convert traffic from the CityOfLinz data to SUMO if we have different IDs in our network map.
2. When attempting to run the simulation, I encountered the following errors:
```
Loading net-file from 'osm.net.xml.gz' ... 
Error: Unknown vehicle class 'container' encountered.
Error: Unknown vehicle class 'cable_car' encountered.
Error: Unknown vehicle class 'subway' encountered.
Error: Unknown vehicle class 'aircraft' encountered.
Error: Unknown vehicle class 'wheelchair' encountered.
Error: Unknown vehicle class 'scooter' encountered.
Error: Unknown vehicle class 'drone' encountered.
Error: Unknown vehicle class 'container' encountered.
Error: Unknown vehicle class 'cable_car' encountered.
Error: Unknown vehicle class 'subway' encountered.
Error: Unknown vehicle class 'aircraft' encountered.
Error: Unknown vehicle class 'wheelchair' encountered.
Error: Unknown vehicle class 'scooter' encountered.
Error: Unknown vehicle class 'drone' encountered.
```
Could you clarify the need for these vehicle classes? Perhaps we should focus on regular vehicles initially, and then consider incorporating aircraft, drones, etc.
3. Could you explain the necessity of polygons and other aesthetic elements? These additions may significantly impact simulation performance as we scale up.

**Comment by amirhesama** [comment]
Hello Nikita,

This was primarily a test without a specific purpose, intended to gather your feedback and determine the direction I should take.

1. No, I didn't use those files as it was just a test, and I should have utilized your real dataset, but I'm not entirely familiar with its structure.
2. That's correct, we require regular ones.
3. There's no scientific reason behind this—just a test, and you're right.

As you can tell, I'm not well-versed in SUMO, and I realize numerous mistakes were made, even in this test. I'd like to mention that I could also follow the hints you provided, but it's more time-consuming than employing AI tools on the data we can extract from this simulation for further analysis.

You're aware that at this time, Cristina needs a paper from this project, and I'm unsure if you have commenced writing something in a paper format for your findings and work on this project. If you haven't started yet, and considering it also takes time, I could handle it, or we could divide the tasks. For instance, if I have the data from SUMO from all the agents, I could perform several tasks with AI to be at least helpful in this project, because, as you mentioned before, and even now, I believe that time is limited, and we require a paper. Given that I'm new to SUMO, should we focus on using AI methods and commence writing the paper, or anything else you think is suitable? Because Cristina has repeatedly emphasized the need for a paper and analysis involving AI, which I can conduct.

I eagerly anticipate your thoughts on the best and quickest solution to tackle this paper.

Kind regards,
Amirhesam
